#! /bin/zsh

DOTFILES_DIR=$HOME/Dropbox/dotfiles

for file in `find "$DOTFILES_DIR" -name '.*' | grep -v "dotfiles/.git$" | perl -nle 'm!dotfiles/(.+)$! and print $1'`; do
  ln -si $DOTFILES_DIR/$file $HOME/$file
done
